### ISSUE TITLE
Android does not scroll when I use it with @gorhom / react-native-bottom-sheet 

### ISSUE THREAD

**Issue by mehderilker** [erksch/react-native-wheely#20] opened 2022-01-28 15:39 UTC
Hi,

Works great on iOS devices when I use it with the @gorhom/react-native-bottom-sheet repo. But it does not scroll on Android devices.

IOS Working:

https://user-images.githubusercontent.com/26353461/151572072-2448df8e-91f8-4d77-8069-8543cccb52ce.mp4

Android Not Working:

https://user-images.githubusercontent.com/26353461/151574864-76fe75f2-4126-4976-bc5a-1a21d12aec5a.mp4

Example Code:

```
import React, {useCallback,useRef,useMemo) from 'react'
import BottomSheet, {
  BottomSheetView
} from '@gorhom/bottom-sheet';
import WheelPicker from 'react-native-wheely';
const Example = () => {
  const snapPoints = useMemo(() => ['30%', '50%', '60%', '90%'], []);
  const renderBackdrop = useCallback(
    props => (
      <BottomSheetBackdrop
        disappearsOnIndex={-1}
        appearsOnIndex={0}
        {...props}
      />
    ),
    [],
  );

  const ref = useRef(null);
const handleSheetChanges = useCallback(index => {
    console.log('handleSheetChange', index);
  }, []);
  const handleSnapPress = useCallback((index, refId) => {
    console.log('handleSnapPress', index, refId);
    ref.current?.snapToIndex(index);
  }, []);
  const handleClosePress = useCallback(refId => {
    ref.current?.close();
  }, []);

return(
<View>
   <BottomSheet
        index={1}
        backdropComponent={backdropComponent}
        animateOnMount={true}
        enablePanDownToClose={true}
        keyboardBehavior="extend"
        handleIndicatorStyle={{
          backgroundColor: '#E4E7EC',
          width: scale(70),
        }}
        handleStyle={{backgroundColor: '#F9FAFB', borderRadius: 10}}
        ref={ref}
        snapPoints={snapPoints}
        onChange={handleSheetChanges}>
         <BottomSheetView>
  <WheelPicker
          selectedIndex={selectedIndex}
          containerStyle={styles.container}
          selectedIndicatorStyle={styles.selectedIndicator}
          itemTextStyle={styles.itemText}
          itemStyle={styles.item}
          options={options}
          onChange={onChange}
        />
  </BottomSheetView>

    </BottomSheet>
    </View>
)
}
```

Dependency:
```
    "@gorhom/bottom-sheet": "^4.1.5",
    "react-native-reanimated": "^2.3.1",
    "react-native-gesture-handler": "^2.1.1",
    "react-native-wheely": "^0.3.2",
```

**Comment by erksch** [comment] 2022-01-28 19:05
Are you sure the problem is with react-native-wheely? Have you tried some other normal ScrollViews / FlatList on Android and verified that that works?

**Comment by SrBrahma** [comment] 2022-03-01 03:26
Hi @erksch, I am also having the scroll issue with my modal using your wheely.

Check this: https://github.com/rheng001/react-native-wheel-scrollview-picker/issues/14#issuecomment-1027645512

I have my own "wheely" but I wanted to try yours.

**Comment by erksch** [comment] 2022-03-18 14:19
I have found the problem, it happens when the WheelPicker is used inside of some other pressable view that handles touch inputs. 

You should be able to wrap the WheelPicker component like so:

```typescript
<View onStartShouldSetResponder={() => true} style={{ backgroundColor: 'transparent' }}>
     <WheelPicker ... />  
</View>
```

to catch gesture inputs and "reserve" them for the wheel picker.

**Comment by kadirucsu** [comment] 2022-07-26 21:53
`<BottomModal
        enableContentPanningGesture={false} .... />`

this way it works for me

**Comment by erksch** [comment] 2022-08-01 16:39
It seems that a `FlatList` nested in another `FlatList` or `ScrollView` [is not supported on Android](https://github.com/facebook/react-native/issues/15375). On iOS, it works fine.

**Comment by enestatli** [comment] 2022-09-02 18:02
@erksch Try to wrap your BottomSheet children with `<NativeViewGestureHandler style={styles.fill} ref={gestureRef}>` and add `waitFor={gestureRef}` to your BottomSheet

**Comment by BagerYF** [comment] 2022-12-07 01:28
BottomSheet set `enableContentPanningGesture={false}`
it works.

**Comment by erksch** [comment] 2023-01-21 23:58
Seems like people found a solution! Closing this :)

**Closed by erksch** 2023-01-21 23:58 UTC

**Comment by izner32** [comment] 2025-05-10 16:38
If you want the enableContentPanningGesture to still be enabled, do the following below: 

```
import { ScrollView } from "react-native-gesture-handler";

<WheelPicker
    flatListProps={{
        renderScrollComponent: (props) => (
            <ScrollView className="flex-1" {...props} />
        )
    }}
    // ...
/>
```
